#!/bin/sh

moon check

echo "Running non-SVG tests..."
moon test
TEST_EXIT=$?

if [ $TEST_EXIT -ne 0 ]; then
  echo "Pre-commit check failed: non-SVG tests did not all pass."
  exit 1
fi

echo "All non-SVG tests passed."